spring:
  application:
    name: smcccms-backend
  
  datasource:
    url: jdbc:postgresql://localhost:57542/smcccms
    username: ${DB_USERNAME:smcccms_admin}
    password: ${DB_PASSWORD:SMCCCMSdemo}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-migration-naming: true
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  
  mvc:
    throw-exception-if-no-handler-found: true
  
  web:
    resources:
      add-mappings: false

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SPRINGDOC_ENABLED:true}
    path: /swagger-ui
    try-it-out-enabled: true
    operations-sorter: method
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

# User Provider Configuration
user:
  provider:
    base-url: ${USER_PROVIDER_BASE_URL:http://localhost:8081}
    username: ${USER_PROVIDER_USERNAME:demo}
    password: ${USER_PROVIDER_PASSWORD:demo}

# Session Configuration  
session:
  secret: ${SESSION_SECRET:smcccms-demo-secret-key-change-in-production}

logging:
  level:
    root: INFO
    uk.gov.demo.smcccms: DEBUG
    org.springframework.web: INFO
    org.springframework.jdbc: DEBUG
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"